const PAYMENT_METHOD_TYPE = {
  BANK: 'BANK',
  ATM: 'ATM',
  APPLE: 'APPLE',
  GOOGLE: 'GOOGLE',
};

const PAYMENT_STEP = {
  CHOOSE_PACKAGE: 0,
  PAYMENT: 1,
  COMPLETED: 2,
};

export { PAYMENT_METHOD_TYPE, PAYMENT_STEP };
